name: Auto-request Codex Review

# Automatically trigger Codex review on PRs
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  request-codex-review:
    runs-on: ubuntu-latest

    # Only needed permissions
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Request Codex review via comment
        uses: actions/github-script@v7
        with:
          script: |
            // Post a comment that triggers Codex to review the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `@codex review

Please review this PR focusing on:
- **Code Quality**: SOLID principles, DRY violations, type hints
- **Bugs & Edge Cases**: Potential issues, security concerns
- **Cost Optimization**: Opportunities to reduce LLM API costs
- **Idempotency**: Verify operations are safe to re-run
- **Project Guidelines**: Check adherence to CLAUDE.md principles

Context: This is the Media Digest project - a personal tool that processes podcasts/newsletters into Obsidian notes. Target budget: $15/month.`
            });
